### ISSUE TITLE
User Story 2 - Make a reservation

### ISSUE THREAD

**Issue by zinebbamouh** [apollinelbcr/team_1-soen341projectW2024#2]
### Description: 

As a user, I want to be able to start my reservation by providing a location, and a pickup and return date and specific criteria such as car type, category and price, so I can have precise results to make the best choice.

| Risk | Priority | Story Points |
| :---:         |     :---:      |          :---: |
| very high  |  very high    |  12   |

### Tasks List:

- [x] Implement User Authentification
* Make it possible for the user to create an account
* Allow user to change its personal account information such as first name, last name, email, password, etc.

- [x] Implement Database for User's Account
* Collect and store user's account informations

- [x] Implement Extra Equipment Option
* Let the user choose if they want to add extra equipment at an additional price
 
- [x] Implement Find Nearest Branch Option
* User provides its location (postal code, city, airport) to get all the nearest branch

- [x] Implement Review Section 
* After renting a car, user can leave a rating and optional brief review
