### ISSUE TITLE
User Story 8 : Find a Branch

### ISSUE THREAD

**Issue by kaoutar98** [apollinelbcr/team_1-soen341projectW2024#37]
### Description: 
As a user, I want to be able to find the nearest branch of the rental company, so I can easily locate it when I want to rent a vehicle. This feature provides users with a convenient way to search for and locate the closest rental branch based on their current location. By integrating Google Maps API and implementing a search functionality, users can effortlessly find branch locations, ensuring a seamless rental experience.

| Risk | Priority | Story Points |
| :---:         |     :---:      |          :---: |
| high  |  high    |  10   |

### Tasks List:
- [ ] #72 
- [ ] #88 
- [ ] Select and view car details
- [ ] Choose rental options
- [ ] Check availability and price 
- [ ] Confirm Booking 
- [ ] Provide payment information

### Sequence Diagram
<img width="952" alt="Screenshot 2024-03-25 at 5 39 08 PM" src="https://github.com/apollinelbcr/team_1-soen341projectW2024/assets/51494218/1707c9c1-7fe1-416e-8650-459952400d76">

### Activity Diagram
<img width="841" alt="Screenshot 2024-03-25 at 5 42 04 PM" src="https://github.com/apollinelbcr/team_1-soen341projectW2024/assets/51494218/7b1ae2b1-0931-43d6-bc12-ff741970ea42">
