### ISSUE TITLE
User Story 10 : Check-out Process

### ISSUE THREAD

**Issue by kaoutar98** [apollinelbcr/team_1-soen341projectW2024#39]
### Description: 
As a user, I want a simple check-out process when returning my rented vehicle, ensuring all payments and documentation are processed efficiently. 

The check-in process facilitates a smooth transition for users returning their rented vehicles. Users can input vehicle condition details through a user-friendly form, which is then processed and stored securely in the database. 

| Risk | Priority | Story Points |
| :---:         |     :---:      |          :---: |
| very high  | very high  |  15   |

### Tasks List:
- [ ] Design database schema to store check-out information and calculate total payment (days + extras (if applied) + taxes + deposit).
- [ ] Develop a check-out form for users to confirm return details and make payment.
- [ ] Implement backend logic to process check-out, calculate payment, and update vehicle availability.
- [ ] Mock payment gateway or similar feature to process the checkout.

### Sequence Diagram
<img width="902" alt="Screenshot 2024-03-25 at 6 08 42 PM" src="https://github.com/apollinelbcr/team_1-soen341projectW2024/assets/51494218/83b8ac5a-0142-4da6-8d08-4e0ad1fc276a">

### Activity Diagram
<img width="536" alt="Screenshot 2024-03-25 at 6 09 27 PM" src="https://github.com/apollinelbcr/team_1-soen341projectW2024/assets/51494218/9efc17e0-9500-4921-b8a0-f433861273dc">
