### ISSUE TITLE
User Story 3 - Manage Reservation

### ISSUE THREAD

**Issue by zinebbamouh** [apollinelbcr/team_1-soen341projectW2024#6]
### Description
As a user, I want to be able to view, modify, and cancel reservation by accessing my account, so I can keep track and have controle on them.

| Risk | Priority | Story Points |
|    :---:     |     :---:      |   :---:   |
| high  |  medium   |  3  |

#### Task List:

- [x] Design a User-Friendly Interface for accessing reservations easily
* Neat design 
* Implement a dashboard to access easily the user account
* Reservations should contain essentials details of the car

- [x] User can modify the reservation
* Can modify the pick up and drop off dates
* Can modify the pick up and drop off location
* Can add or remove extra equipment

- [x] User can delete the reservation
